# Generated by Django 4.1.5 on 2023-03-30 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broomk', '0002_hotels_country_hotels_state_alter_hotels_name_rooms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='name',
            field=models.CharField(default='Broomk', max_length=30),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='state',
            field=models.CharField(default='Punjab', max_length=50),
        ),
    ]
