# Generated by Django 4.1.5 on 2023-04-10 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broomk', '0005_remove_rooms_payprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='room_type',
            field=models.CharField(choices=[('1', 'premium'), ('2', 'deluxe'), ('3', 'regular')], max_length=50),
        ),
    ]
